---
title: "Wybory 2019 - IPSOS"
author: "@mbojan"
editor_options: 
  chunk_output_type: console
---


```{r setup}
library(tidyverse)
library(rvest)

options(
  tibble.print_min = Inf
)
```


# Dane

## Wybory 2019


Dane IPSOSa dla TVN24:

```{r download-ipsos}
# d <- jsonlite::fromJSON("~/Downloads/ipsos_results.json") %>%
wybory2019 <- jsonlite::fromJSON("https://wybory.online.tvwisla.com.pl/uploads/ipsos_results.json") %>%
  unlist() %>%
  enframe() %>%
  mutate(
    l = strsplit(name, "\\."),
    depth = map_int(l, length),
    what = map_chr(l, 1),
    path = map(l, head, -1),
    partia = map_chr(l, tail, 1)
  )
```

Ile czego:

```{r}
wybory2019 %>%
  distinct(what, depth) %>%
  knitr::kable()
```


## Sejm 2015

Wyniki wyborów parlamentarnych 2015^[Źródło: https://parlament2015.pkw.gov.pl/349_Wyniki_Sejm.html]

```{r wybory2015}
r <- xml2::read_html(
  "https://parlament2015.pkw.gov.pl/349_Wyniki_Sejm.html"
)

sejm2015 <- rvest::html_table(r, fill=TRUE)[[1]] %>%
  as_tibble(.name_repair = "unique") %>%
  filter(!is.na(Procent)) %>%
  select(-starts_with("...")) %>%
  mutate_at(
    c("Zdobyte głosy", "Procent"),
    ~ as.numeric(gsub("[^0-9.]", "", .))
  ) %>%
  mutate(
    komitet2019 = recode(
      `Nazwa komitetu`,
      "Komitet Wyborczy Prawo i Sprawiedliwość" = "PiS",
      "Komitet Wyborczy Platforma Obywatelska RP" = "PO",
      "Komitet Wyborczy Wyborców \"Kukiz'15\"" = "Kukiz",
      "Komitet Wyborczy Nowoczesna Ryszarda Petru" = "Nowoczesna",
      "Koalicyjny Komitet Wyborczy Zjednoczona Lewica SLD+TR+PPS+UP+Zieloni" = "Lewica",
      "Komitet Wyborczy Polskie Stronnictwo Ludowe" = "PSL",
      "Komitet Wyborczy KORWiN" = "Korwin",
      "Komitet Wyborczy Partia Razem" = "Razem",
      .default = "Inne partie i ugrupowania"
    )
  )
```


## Sejm 2019


```{r}
txt <- "Komitet	Liczba głosów	Procent głosów	Liczba mandatów	Procent mandatów
KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ	8 051 935	
43,59%
	235	
51,09%
KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO .N IPL ZIELONI	5 060 355	
27,40%
	134	
29,13%
KOMITET WYBORCZY SOJUSZ LEWICY DEMOKRATYCZNEJ	2 319 946	
12,56%
	49	
10,65%
KOMITET WYBORCZY POLSKIE STRONNICTWO LUDOWE	1 578 523	
8,55%
	30	
6,52%
KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ	1 256 953	
6,81%
	11	
2,39%
KOMITET WYBORCZY WYBORCÓW KOALICJA BEZPARTYJNI I SAMORZĄDOWCY	144 773	
0,78%
	0	
0,00%
KOMITET WYBORCZY WYBORCÓW MNIEJSZOŚĆ NIEMIECKA	32 094	
0,17%
	1	
0,22%
KOMITET WYBORCZY SKUTECZNI PIOTRA LIROYA-MARCA	18 918	
0,10%
	0	
0,00%
KOMITET WYBORCZY AKCJA ZAWIEDZIONYCH EMERYTÓW RENCISTÓW	5 448	
0,03%
	0	
0,00%
KOMITET WYBORCZY PRAWICA	1 765	
0,01%
	0	
0,00%"

w2019 <- textConnection(txt) %>%
  readLines() %>%
  strsplit("\t") %>%
  unlist() %>%
  "["(-which(. == "")) %>%
  matrix(ncol=5, byrow=TRUE)
nams <- w2019[1,]

sejm2019 <- w2019[-1,] %>%
  as_tibble() %>%
  set_names(nams) %>%
  mutate_at(
    - 1,
    ~ gsub(",", ".", .x) %>%
      gsub("[^0-9.]", "", .) %>%
      as.numeric()
  )
```


# Joint probability of 2015 x 2019

Extract the conditional distributions of voting:

```{r}
# Row pct: P(2019 | 2015)
drow <- wybory2019 %>%
  filter(what == "SEJM_2015_row") %>%
  transmute(
    w2015 = map_chr(path, 2),
    w2019 = partia,
    pct = value
  )

rowtab <- with(drow, tapply(pct, list(w2015, w2019), identity)) / 100

stopifnot(isTRUE(all.equal(
  rowSums(rowtab),
  rep(1, nrow(rowtab)),
  check.attributes = FALSE
)))
  

# Col pct: P(2015 | 2019)
dcol <- wybory2019 %>%
  filter(what == "SEJM_2015_col") %>%
  transmute(
    w2015 = map_chr(path, 2),
    w2019 = partia,
    pct = value
  ) %>%
  arrange(w2019, w2015)

coltab <- with(dcol, tapply(pct, list(w2015, w2019), identity)) / 100

stopifnot(isTRUE(all.equal(
  colSums(coltab),
  rep(1, ncol(coltab)),
  check.attributes = FALSE
)))
```

Computing steady states of the Markov Chains:

```{r}
p1 <- t(coltab) %*% rowtab
mc1 <- new("markovchain", transitionMatrix = p1)
mcss1 <- steadyStates(mc1)

p2 <- rowtab %*% t(coltab)
mc2 <- new("markovchain", transitionMatrix = p2)
mcss2 <- steadyStates(mc2)
```

Checking compatibility

```{r}
m1 <- sweep(rowtab, 1, mcss2, "*")
m2 <- sweep(coltab, 2, mcss1, "*")
all.equal(m1, m2)
```

```{r}
hist(abs(m1 - m2))
```

Not exactly compatible.


Let's proceed with `m1`.

```{r}
m1 %>%
  as.table() %>%
  as.data.frame(stringsAsFactors=FALSE) %>%
  as_tibble() %>%
  mutate(n = Freq * 60000) # get counts
```












# Przepływy: Sejm

```{r flows-sejm}
flows2019 <- wybory2019 %>%
  filter(what == "SEJM_2015_row") %>%
  transmute(
    w2015 = map_chr(path, 2),
    w2019 = partia,
    pct = value
  ) %>%
    left_join(
    sejm2015 %>%
      group_by(komitet2019) %>%
      summarise(glosy2015 = sum(`Zdobyte głosy`)),
    by=c("w2015"="komitet2019")
  ) %>%
  filter(!is.na(glosy2015)) %>%
  mutate(
    glosy = pct / 100 * glosy2015
  )
```

```{r flows-sejm-alluvial}
with(
  flows2019,
  alluvial::alluvial(
    select(flows2019, w2015, w2019),
    freq = glosy,
    col = match(w2019, unique(w2019))
  )
)
```

